### ISSUE TITLE
Offer as installable package via package.el?

### ISSUE THREAD

**Issue by NateEag** [emacs-lsp/lsp-php#1]
I'd been using [my own lame lsp-php backend](https://github.com/NateEag/.emacs.d/commit/2cf716fa62e8476b600686b5f3989bced4522eb1#diff-1986f225edad98d16065f5aa9d64011a) for a while and thinking I'd get around to submitting a cleaner one to the emacs-lsp organization eventually.

Now that one exists, could we make it installable via package.el somehow? 

I'm currently running a version [that's already available via MELPA](https://melpa.org/#/lsp-php), but I'd rather run one that belongs to the org than a specific individual.

**Comment by cmack** [comment]
Unfortunately because both this and the one in MELPA have the same name, it's already leading to confusion. https://www.reddit.com/r/emacs/comments/7xz6bd/im_having_the_worst_time_trying_to_get_php/

**Comment by NateEag** [comment]
I've suggested adding a package with a similar name over at the MELPA repo, in hopes that could reduce the confusion.

If anyone has better ideas, maybe hop into the thread over there?

**Comment by cmack** [comment]
```elisp

**Comment by purcell** [comment]
Can you and @tszg please jointly decide what to do? The best outcome would obviously be a single actively-maintained and working `lsp-php` which satisfies everyone involved. It doesn't really matter to MELPA which organisation it lives in.

**Comment by NateEag** [comment]
I don't actually own this repo, but I'll see if I can get some conversation started.

**Comment by Declspeck** [comment]
Turns out I had to explicitly watch this repository to get notifications for new issues. I was blissfully unaware of this issue before I was mentioned in the other issue. 

I made a pull-request towards this repository, porting changes from tszg/lsp-php to this repository: #3

**Comment by NateEag** [comment]
Ah, makes sense. No worries.

Thanks for working on this!

**Comment by Fuco1** [comment]
Any updates here? Seems like this is also a duplicate of #2 so I think both can be resolved when we switch the recipe.

**Comment by tam5** [comment]
can this be closed now?

**Comment by Fuco1** [comment]
This whole package is probably no longer necessary since lsp-mode now bundles clients in the core.

**Comment by NateEag** [comment]
@Fuco1 Makes sense. I didn't even realize there was a bundled client now - I'll have to switch over to it.

Closing issue accordingly.
