### ISSUE TITLE
LSP doesn't run with first open file and subsequent files fail

### ISSUE THREAD

**Issue by echosa** [emacs-lsp/lsp-php#11]
I open Emacs and open a PHP file. LSP doesn't load. It's not in the mode line, etc. This is possibly due to using `use-package`, but I'm not sure.

However, if I close the file and open it again (or open a second PHP file), LSP does run (it's in the mode line when the file eventually loads) but LSP seems to be failing.

In `*Messages*` I see:

```
/home/echosa/<project dir>/: lsp-php has exited (exited abnormally with code 1)
File mode specification error: (lsp-timed-out-error)
Error running timer ‘lsp-ui-sideline--run’: (wrong-type-argument hash-table-p nil)
```

The `*lsp-php stderr*` buffer only has this:

```
Process lsp-php stderr finished
```

This is my config. You'll notice that I don't have `use-package` ensuring `lsp-php`. That's because I saw in a different Github issue that the Melpa version it out of date, so I manually cloned this repo, add it to the load-path manually, and then let `use-package` handle its setup.

```
(use-package php-mode
  :ensure t
  :mode "\\.php\\'"
  :init
  (add-hook 'php-mode-hook #'lsp-mode))

(use-package company
  :ensure t
  :hook (prog-mode . global-company-mode)
  :config
  (setq company-idle-delay 0.3)
  (setq company-minimum-prefix-length 1)
  (setq company-tooltip-align-annotations t))

(use-package company-lsp
  :ensure t
  :after (lsp-mode company)
  :config
  (push 'company-lsp company-backends))

(use-package lsp-ui
  :ensure t
  :after lsp-mode
  :hook (lsp-mode . lsp-ui-mode))

(add-to-list 'load-path "~/.emacs.d/lsp-php")
(use-package lsp-php
  :after (php-mode lsp-mode)
  :init
  (add-hook 'php-mode-hook #'lsp-php-enable))
```

**Comment by Ramapitecus** [comment]
You have 2 functions added to the `'php-mode-hook` you should only have `#'lsp-php-enable` maybe that's the cause of your issue

**Comment by Ramapitecus** [comment]
This is what I have. And also the package in melpa points to this one now. That is fixed. 
```
(use-package php-mode
  :ensure t
  :config
  ;; indent -> calls next line like symfony2
  (add-hook 'php-mode-hook 'php-enable-symfony2-coding-style)
  ;; aline -> on successive lines
  (setq php-lineup-cascaded-calls t)
  ;; don't use things only needed for html (my files are php only)
  (setq php-template-compatibility nil))

;; lsp
;; https://github.com/emacs-lsp/lsp-php
;; from https://www.reddit.com/r/emacs/comments/7xz6bd/im_having_the_worst_time_trying_to_get_php/
(use-package lsp-mode
  :ensure t
  :config
  (setq lsp-response-timeout 25))

(use-package lsp-ui
  :ensure t
  :after lsp-mode
  :config
  (add-hook 'lsp-mode-hook 'lsp-ui-mode))

;; moved to lsp-ui
;; (use-package lsp-flycheck
;;   :ensure f ; comes with lsp-mode
;;   :after (lsp-mode flycheck))

(use-package company-lsp
  :ensure t
  :after (lsp-mode company)
  :config
  (push 'company-lsp company-backends))

(use-package lsp-php
  :after (php-mode lsp-mode)
  :ensure t
  :config
  (add-hook 'php-mode-hook #'lsp-php-enable)
  (custom-set-variables
   ;; Composer.json detection after Projectile.
   '(lsp-php-workspace-root-detectors (quote (lsp-php-root-projectile lsp-php-root-composer-json "index.php" "robots.txt")))
))
```

**Comment by echosa** [comment]
I replaced my init with yours, and one problem is solved: I don't have to open two PHP files for the LSP to run. It happens with the first PHP file now, so that's an improvement.

However, I still get the same errors as before, in both`*Messages*` and `*lsp-php stderr*`.

**Comment by Ramapitecus** [comment]
Are you sure it's finding the language server? and that it's running correctly?

**Comment by echosa** [comment]
I reinstalled the language server and it seems to be working now! It's been parsing my project for approaching an hour now. (It's a really big project.) 

Where does the language server cache what it is parsing? I don't see anything in my project directory nor in the language server directory.

**Comment by Ramapitecus** [comment]
I've not read about a cache. It parses it every time for me (I restart emacs maybe once a week or less). Make sure to have xdebug disabled.

**Comment by echosa** [comment]
If it has to parse every time I start Emacs and open the project, then it is absolutely useless to me. I can't afford to wait an hour every time I open the project. :-( That's a shame, because I've been playing with it since it parsed last night, and it's pretty sweet.

**Comment by Ramapitecus** [comment]
So, you made sure to disable xdebug? then restart your webserver, then start lsp?

**Comment by echosa** [comment]
What do you mean restart the webserver? The webserver is on a VM, and the VM has been shutdown when I've been testing out LSP. Consequently, xdebug is also off, since the VM is shutdown.

The project we have is pretty big. Over 47,000 files end up indexed by the LSP. The project source directory is several gigs (even when ignoring `.git/`). Perhaps a project of that size just always takes a super long time to parse? 

Also, it turns out that the PHP LSP by default does cache some things to the hard disk, which is good, but it only caches vendor code, not the first-party source code. Even with that, it still takes a long time to parse the project. I really want to use this, but like I said, I can't afford to wait 30 min, an hour, or more every time I open the project. I'll keep an eye on the LSP in case it gets improved to be faster. It doesn't seem like there's a way to ignore directories, which would be helpful.

**Comment by Ramapitecus** [comment]
ok then, seems that you would have to wait every time you start emacs. Our projects are smaller, and takes only a couple of minutes. But as I said, I only restart emacs one every couple of weeks probably. Either way, this issue should be closed.

**Comment by echosa** [comment]
Thanks for the info and helping me get it to a mostly working state!
