### ISSUE TITLE
Company Completions are Extremely Slow

### ISSUE THREAD

**Issue by tam5** [emacs-lsp/lsp-php#13]
Completion with company for lsp-php is very slow and lags the rest of the editor.

Jumping to definition is working very nicely, it is just the auto complete that is lagging behind significantly.

Here is my configuration:

```
(use-package company
  :ensure t
  :config (progn
            (defvar company-dabbrev-downcase)
            (setq company-dabbrev-downcase nil)
            (setq company-idle-delay 0)
            (add-to-list 'company-backends '(company-capf company-dabbrev))
            (add-hook 'after-init-hook 'global-company-mode)))

(use-package php-mode :ensure t)
(use-package lsp-mode :ensure t)
(use-package lsp-php :ensure t)

(setq lsp-php-server-install-dir "~/.emacs.d/packages/php-language-server")
(add-hook 'php-mode-hook #'lsp-php-enable)
```

I have also tried to force company to only use `compnay-capf`, as well as have tried to use `company-lsp`, but so far they all give me the same result.

I'm actually not sure where the issue lies, I almost doubt it is actually `lsp-php` that is causing this issue, but I will start here.

Has anyone been able to use company for lsp-php satisfactorily? 

(Here's a preview)
![recording](https://user-images.githubusercontent.com/11488762/44632579-344e7b00-a94b-11e8-814b-c6f18688aa9a.gif)

**Comment by cmatzenbach** [comment]
@tam5 I'm having the exact same issue - did you ever find a solution to this or did you just stop using the package and close the issue?

**Comment by tam5** [comment]
@cmatzenbach , I have not found a satisfactory solution, but the more I looked into it, the less sure I was of where the problem lied, so I closed the issue.

I still plan on figuring out how to get things working properly, I have not had the time for a while, but I can keep you posted.

For now, I have been using [ac-php](https://www.uplabs.com/posts/ruler-vcard-cv-resume-portfolio-html-template) which is not perfect, but very good and has kept me happy enough for quite some time.

**Comment by cmatzenbach** [comment]
Ugggghhhh back to tag tables....well I guess it's better than nothing.  I can't wait till LSP has all the kinks worked out.  Emacs is going to be an incredible editor (the cquery-lsp is incredible and has turned emacs into by FAR the best C IDE I've ever used)

**Comment by tam5** [comment]
@cmatzenbach my thoughts exactly.

I plan on spending a little more time looking at [eglot](https://github.com/joaotavora/eglot), just like @jonnycyr mentioned in the referenced issue. I looked a little while ago, then gave up, and now will try it out again.

I'm still not convinced it is the php language server itself, as i explain [here](https://github.com/tigersoldier/company-lsp/issues/52) because VSCode somehow seems to be able to achieve a satisfactory response time.

I guess let's keep each other posted if stuff gets figured out

**Comment by jonnycyr** [comment]
Eglot works a little bit differently, I believe it caches commands and then sends, instead of sending and waiting for each command. I’d check out this thread on reddit, the creator of eglot responded to it: https://reddit.com/r/emacs/comments/91rtov/what_are_the_best_ways_to_speed_up_lsp_mode/

**Comment by tam5** [comment]
Upon further investigation, it is `php-language-server` itself that is too slow (2+ seconds for completion requets). I think VsCode might hide this by including other results in the completions.

There is already an [issue](https://github.com/felixfbecker/php-language-server/issues/274) on the php langauge server side to address this, so I guess that is where further discussion should go.

**Comment by cmatzenbach** [comment]
Nice find @tam5!!!

**Comment by jonnycyr** [comment]
@cmatzenbach In the mean time, you can still try out eglot - it has some modifications to make it faster. Below is a comment from the plugin's creator from the reddit thread I linked:

> Both eglot and lsp-mode have to send changes to the server. Last time I checked, lsp-mode does it immediately after you press the key, which might choke the server with messages, while eglot collects a bunch of these changes to send after you let go of space (or backspace). So in this particular use case eglot should in theory be faster/more responsive.
